#### timestring "2006-01-02 15:04:05"

actions:
  - action: delete_indices
    description: forcemerge selected indices_test
    options:
      disable_action: false
      delay: 5
    filters:
    - filtertype: pattern
      kind: prefix
      value: logstash-sevone-sn
    - filtertype: space
      disk_space: 650
    # - filtertype: age
    #   source: creation_date
    #   direction: range
    #   unit: days
    #   range_from: 2
    #   range_to: 1



#### adjust 
# actions:
#   - action: delete_indices
#     description: delete selected indices_test
#     options:
#       disable_action: false
#       delay: 5
#     filters:
#     - filtertype: pattern
#       kind: prefix
#       value: logstash-atm-sn
#     - filtertype: water_level
#       upper_limit: 55
#       lower_limit: 54
    # - filtertype: age
    #   source: creation_date
    #   direction: range
    #   unit: days
    #   range_from:
    #   range_to: 0

  # - action: delete_indices
  #   description: delete selected elasticsearch-api-status-calculate
  #   options: 
  #     disable_action: false
  #   filters:
  #   - filtertype: age
  #     source: creation_date
  #     direction: older
  #     unit: days
  #     unit_count: 30
  #   - filtertype: pattern
  #     kind: prefix
  #     value: elasticsearch-api-status-calculate

  # - action: delete_indices
  #   description: delete selected logstash-bde-apache-access
  #   options: 
  #     disable_action: false
  #   filters:
  #   - filtertype: age
  #     source: creation_date
  #     direction: older
  #     unit: days
  #     unit_count: 2
  #   - filtertype: pattern
  #     kind: prefix
  #     value: logstash-bde-apache-access