#### timestring "2006-01-02 15:04:05"
#### adjust 
actions: 
  - action: delete_indices
    description: delete selected elasticsearch-api-status
    options: 
      disable_action: false
      delay: 5
    filters:
    - filtertype: age
      source: creation_date
      direction: older
      unit: days
      unit_count: 30
    - filtertype: pattern
      kind: prefix
      value: elasticsearch-api-status